In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  3.6893e+19  0.0000e+00
 3.6893e+19  7.0065e-45  0.0000e+00
 2.2421e-44  0.0000e+00  0.0000e+00
 3.6893e+19  0.0000e+00  3.6893e+19
 4.2039e-45  3.6893e+19  0.0000e+00
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [3]:
x = torch.rand(5, 3)
print(x)


 0.9515  0.3572  0.6437
 0.3152  0.9865  0.2069
 0.5204  0.8397  0.1056
 0.5215  0.3288  0.3918
 0.3965  0.2512  0.3027
[torch.FloatTensor of size 5x3]



Get its size



In [4]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [5]:
y = torch.rand(5, 3)
print(x + y)


 1.5648  1.2711  1.2193
 1.0180  1.1051  1.2057
 0.7331  1.3913  1.0535
 0.6136  0.7273  0.4605
 1.2021  1.0146  1.2915
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [6]:
print(torch.add(x, y))


 1.5648  1.2711  1.2193
 1.0180  1.1051  1.2057
 0.7331  1.3913  1.0535
 0.6136  0.7273  0.4605
 1.2021  1.0146  1.2915
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.5648  1.2711  1.2193
 1.0180  1.1051  1.2057
 0.7331  1.3913  1.0535
 0.6136  0.7273  0.4605
 1.2021  1.0146  1.2915
[torch.FloatTensor of size 5x3]



Addition: in-place



In [8]:
# adds x to y
y.add_(x)
print(y)


 1.5648  1.2711  1.2193
 1.0180  1.1051  1.2057
 0.7331  1.3913  1.0535
 0.6136  0.7273  0.4605
 1.2021  1.0146  1.2915
[torch.FloatTensor of size 5x3]



In [18]:
y.resize_(y.shape[0]*y.shape[1],1)
print(y)


 1.5648
 1.2711
 1.2193
 1.0180
 1.1051
 1.2057
 0.7331
 1.3913
 1.0535
 0.6136
 0.7273
 0.4605
 1.2021
 1.0146
 1.2915
[torch.FloatTensor of size 15x1]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [9]:
print(x[:, 1])


 0.3572
 0.9865
 0.8397
 0.3288
 0.2512
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [10]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [11]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [12]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [14]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y